Layout/ExtraSpacing:
  Enabled: true
  AllowForAlignment: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*.rb

Metrics/ClassLength:
  Enabled: true
  Max: 150

Metrics/MethodLength:
  Enabled: true
  Max: 20

Naming/FileName:
  Exclude:
    - lib/inclusive-code.rb

AllCops:
  TargetRubyVersion: 2.4
