# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in inclusive-code.gemspec
gemspec

gem 'rake'
gem 'rspec'
gem 'rubocop', '~> 0.93.1' # , github: 'rubocop-hq/rubocop'
